export const CSS = String.raw`
.nrs-root{position:relative;min-width:0}
.nrs-triggers{display:flex;align-items:center;gap:4px;height:28px;min-width:0}
.nrs-model-trigger,.nrs-effort-trigger{display:flex;align-items:center;gap:4px;min-width:0;height:28px;padding:0 6px 0 9px;border:0;border-radius:24px;outline:0;background:transparent;color:var(--dsw-alias-label-secondary);font-family:inherit;font-size:13px;font-weight:500;line-height:20px;cursor:pointer}
.nrs-model-trigger{max-width:min(280px,36cqw)}
.nrs-effort-trigger{flex:none;padding-left:8px;color:var(--dsw-alias-label-caption)}
.nrs-model-trigger:hover:not(:disabled),.nrs-effort-trigger:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}
.nrs-model-trigger:focus-visible,.nrs-effort-trigger:focus-visible{box-shadow:0 0 0 2px var(--dsw-alias-border-l3)}
.nrs-model-trigger:disabled,.nrs-effort-trigger:disabled{color:var(--dsw-alias-label-dimmed);cursor:default}
.nrs-trigger-model{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.nrs-chevron{flex:none;color:var(--dsw-alias-label-caption);transition:transform 120ms ease}
.nrs-chevron.is-open{transform:rotate(180deg)}
.nrs-menu{position:absolute;right:0;bottom:calc(100% + 8px);z-index:20;display:flex;flex-direction:column;width:max-content;min-width:min(272px,calc(100vw - 32px));max-width:min(420px,calc(100vw - 32px));max-height:min(380px,calc(100vh - 96px));overflow:hidden;padding:4px;border:1px solid var(--dsw-alias-border-inverted);border-radius:12px;background:var(--dsw-specific-menu);box-shadow:var(--dsw-shadow-lv3);color:var(--dsw-alias-label-primary)}
.nrs-effort-popover{position:absolute;right:0;z-index:21;width:min(296px,calc(100vw - 24px));padding:4px;border:1px solid var(--dsw-alias-border-inverted);border-radius:12px;background:var(--dsw-specific-menu);box-shadow:var(--dsw-shadow-lv3);color:var(--dsw-alias-label-primary)}.nrs-effort-popover.is-down{top:calc(100% + 8px)}.nrs-effort-popover.is-up{bottom:calc(100% + 8px)}
.nrs-cell,.nrs-option{box-sizing:border-box;display:flex;align-items:center;gap:8px;width:100%;border:0;border-radius:10px;outline:0;background:transparent;color:inherit;text-align:left;cursor:pointer}
.nrs-cell{height:40px;padding:0 10px;font-size:14px;line-height:22px}
.nrs-option{min-height:38px;padding:6px 8px}
.nrs-cell:hover,.nrs-option:hover:not(:disabled),.nrs-option:focus-visible{background:var(--dsw-alias-interactive-bg-hover)}
.nrs-cell-label{flex:none}.nrs-cell-value{flex:1;min-width:0;overflow:hidden;color:var(--dsw-alias-label-tertiary);text-align:right;text-overflow:ellipsis;white-space:nowrap}.nrs-cell-chevron{flex:none;color:var(--dsw-alias-label-tertiary)}
.nrs-models{min-height:0;overflow-y:auto}.nrs-group+.nrs-group{margin-top:4px}.nrs-group-title{position:sticky;top:0;z-index:1;padding:5px 8px 3px;background:var(--dsw-specific-menu);color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px;font-weight:500}
.nrs-option-copy{display:flex;flex:1;flex-direction:column;min-width:0}.nrs-option-name{overflow:hidden;font-size:14px;line-height:20px;font-weight:500;text-overflow:ellipsis;white-space:nowrap}.nrs-option-description{overflow:hidden;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px;text-overflow:ellipsis;white-space:nowrap}.nrs-check{display:grid;place-items:center;flex:0 0 18px}
.nrs-status,.nrs-empty{padding:10px;color:var(--dsw-alias-label-tertiary);font-size:13px;line-height:20px}.nrs-error{display:flex;align-items:flex-start;justify-content:space-between;gap:8px;margin-bottom:4px;padding:7px 8px;border-radius:8px;background:var(--dsw-alias-interactive-bg-hover-danger);color:var(--dsw-alias-state-error-primary);font-size:12px;line-height:18px}.nrs-retry{flex:none;padding:0;border:0;background:transparent;color:inherit;font-family:inherit;font-size:12px;font-weight:600;line-height:18px;cursor:pointer}
.nrs-effort{position:relative;padding:8px;border-radius:9px;background:var(--dsw-alias-bg-module-platform);overflow:hidden;isolation:isolate}
.nrs-levels{position:relative;z-index:5;display:flex;justify-content:space-between;gap:4px;margin-bottom:4px;padding:0 2px}.nrs-level{min-width:0;padding:0;border:0;background:transparent;color:var(--dsw-alias-label-tertiary);font-family:inherit;font-size:10px;font-weight:500;line-height:16px;cursor:pointer;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.nrs-level.is-current{color:var(--dsw-alias-label-primary);font-weight:600}
.nrs-track-wrap{--nrs-thumb-center:calc(14px + (100% - 28px) * var(--nrs-ratio));box-sizing:border-box;position:relative;z-index:2;height:28px;overflow:hidden;border:1px solid color-mix(in srgb,var(--dsw-alias-border-l2) 75%,#11121a);border-radius:9px;background:#d8d4dc;box-shadow:inset 0 1px 2px #45384e20;isolation:isolate}
.nrs-track-background{position:absolute;z-index:0;inset:0;background:linear-gradient(135deg,#e5e2e9,#d8d4dc)}
.nrs-energy-bed{position:absolute;z-index:1;inset:0 auto 0 0;width:var(--nrs-thumb-center);border-radius:8px;background:linear-gradient(90deg,color-mix(in srgb,var(--nrs-color) 9%,transparent),color-mix(in srgb,var(--nrs-color) 24%,transparent));opacity:0;pointer-events:none}.nrs-effort.is-energy .nrs-energy-bed{opacity:var(--nrs-energy-opacity)}.nrs-effort.is-max .nrs-energy-bed{opacity:0}
.nrs-track-dots{position:absolute;z-index:2;inset:0 14px;display:flex;align-items:center;justify-content:space-between;pointer-events:none}.nrs-track-dots i{width:4px;height:4px;border-radius:50%;background:#8c8592;opacity:var(--nrs-dots-opacity)}.nrs-effort.is-max .nrs-track-dots i{opacity:0}
.nrs-energy{position:absolute;inset:0;z-index:3;width:100%;height:100%;pointer-events:none;opacity:0;mix-blend-mode:multiply;transition:opacity .28s ease}.nrs-effort.is-energy .nrs-energy{opacity:var(--nrs-canvas-opacity)}
.nrs-track-thumb{box-sizing:border-box;position:absolute;left:var(--nrs-thumb-center);top:50%;z-index:6;width:27px;height:27px;border:.5px solid #00000014;border-radius:9px;background:linear-gradient(170deg,#fff 0%,#f1f1f2 42%,#dedee1 100%);box-shadow:0 .5px 1px #0000002e,0 2px 6px #00000040,0 5px 12px #00000020,inset 0 .5px #ffffffd9;transform:translate(-50%,-50%);pointer-events:none}
.nrs-range{appearance:none;position:absolute;inset:0;z-index:8;width:100%;height:100%;margin:0;padding:0;border:0;outline:0;background:transparent;cursor:grab;opacity:0}.nrs-range:active{cursor:grabbing}
.nrs-range::-webkit-slider-thumb{appearance:none;width:28px;height:28px}.nrs-track-wrap:has(.nrs-range:focus-visible){outline:2px solid color-mix(in srgb,var(--dsw-alias-state-business-primary,#679efe) 74%,transparent);outline-offset:2px}.nrs-track-wrap:has(.nrs-range:active) .nrs-track-thumb{transform:translate(-50%,-50%) scale(.95)}
body[data-ds-dark-theme] .nrs-track-wrap{background:#0c0c0f;box-shadow:inset 0 1px 3px #00000052}body[data-ds-dark-theme] .nrs-track-background{background:linear-gradient(135deg,#141419,#0c0c0f)}body[data-ds-dark-theme] .nrs-track-dots i{background:#51525a}body[data-ds-dark-theme] .nrs-energy{mix-blend-mode:screen}
.nrs-color-control{position:relative;display:grid;place-items:center;flex:0 0 34px;width:34px;height:34px;border-radius:17px;background:var(--dsw-alias-bg-base);box-shadow:inset 0 0 0 1px var(--dsw-alias-border-l2);cursor:pointer}.nrs-color-control:has(input:focus-visible){box-shadow:0 0 0 2px var(--dsw-alias-border-l3),inset 0 0 0 1px var(--dsw-alias-border-l2)}.nrs-color-control input{position:absolute;width:1px;height:1px;opacity:0}.nrs-color-control span{width:18px;height:18px;border-radius:50%;background:var(--nrs-swatch);box-shadow:inset 0 0 0 1px #ffffff70,0 0 0 1px #00000014}.nrs-color-control.is-disabled{opacity:.45;cursor:default}
.nrs-mode-row{display:flex;align-items:center;gap:16px;width:100%;border-bottom:1px solid var(--dsw-alias-border-l2);padding:18px 0}.nrs-mode-copy{display:flex;flex:1;flex-direction:column;gap:4px;min-width:0}.nrs-mode-title{color:var(--dsw-alias-label-primary);font-size:14px;line-height:22px;font-weight:400}.nrs-mode-description{max-width:460px;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px}.nrs-setting-actions{display:flex;align-items:center;gap:8px;flex:none}.nrs-mode-picker{display:inline-flex;align-items:center;justify-content:space-between;gap:12px;min-width:112px;height:36px;padding:0 14px;border:0;border-radius:18px;outline:0;background:var(--dsw-alias-bg-module-platform);color:var(--dsw-alias-label-primary);font-family:inherit;font-size:14px;line-height:22px;cursor:pointer}.nrs-mode-picker:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}.nrs-mode-picker:focus-visible{box-shadow:0 0 0 2px var(--dsw-alias-border-l3)}
.nrs-model-picker{max-width:220px;min-width:152px}.nrs-model-picker span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.nrs-mode-picker:disabled{color:var(--dsw-alias-label-dimmed);cursor:default}
@media(max-width:640px){.nrs-mode-row{align-items:flex-start;flex-direction:column;gap:10px}.nrs-setting-actions{width:100%;justify-content:flex-end}.nrs-mode-row>.nrs-mode-picker{align-self:flex-end}}
@media(max-width:480px){.nrs-effort-popover{right:-48px;width:min(276px,calc(100vw - 88px))}}
@media(prefers-reduced-motion:reduce){.nrs-chevron,.nrs-track-thumb{transition:none}}
`
